### ISSUE TITLE
cluster_wait script can not proceed next step

### ISSUE THREAD

**Issue by wowzoo** [aws/eks-distro#101]
After I executed create_cluster.sh, then I executed cluster_wait.sh (by the way, cluster_wait.sh has no permission to execute. is it intended?)

cluster_wait.sh has 3 steps

kops validate cluster --wait 10m
kubectl apply -f ./aws-iam-authenticator.yaml
kubectl delete pod -n kube-system -l k8s-app=aws-iam-authenticator

it should go to "kubectl apply" step after "kops validate cluster", but it doesn't.
I tried cluster_wait.sh several times, but the script stops after "kops validate cluster"

with this fail message

```
VALIDATION ERRORS
KIND	NAME					MESSAGE
Pod	kube-system/aws-iam-authenticator-mllms	system-node-critical pod "aws-iam-authenticator-mllms" is pending

Validation Failed
W0103 11:26:40.703155   33617 validate_cluster.go:221] (will retry): cluster not yet healthy

Validation failed: wait time exceeded during validation
```

when I execute the command one by one, I can create cluster without any problems.

**Comment by TerryHowe** [comment]
I think your concerns are addressed with https://github.com/aws/eks-distro/pull/92

If you just break out of the validate cluster and apply the iam auth yaml, it should start up
