### ISSUE TITLE
Update EKS-A for all releases

### ISSUE THREAD

**Issue by kschumy** [aws/eks-distro#1026]

**Comment by markapruett** [comment]
@kschumy Does https://github.com/aws/eks-distro-internal/issues/100 cover this or should we keep this open?

**Comment by kschumy** [comment]
> @kschumy Does [aws/eks-distro-internal#100](https://github.com/aws/eks-distro-internal/issues/100) cover this or should we keep this open?

This issue was just for the 1.22-8 and 1.23-2 releases, and that issues is about automating them. So their different. But this issue should be closed because the PR was merged by EKS-A
