### ISSUE TITLE
Bare metal support

### ISSUE THREAD

**Issue by elgalu** [aws/eks-distro#1065]
Bare metal support would be great so we can have an EKS@AWS + EKS@DC hybrid but slightly consistent K8s solution.

**Comment by TerryHowe** [comment]
Bare metal support will be available in the EKS Anywhere v0.10 release in the next week or two. It'll show up here when it is ready https://github.com/aws/eks-anywhere/releases

**Comment by markapruett** [comment]
Here's the latest release of EKS-A with bare metal support: https://github.com/aws/eks-anywhere/releases/tag/v0.10.0
