### ISSUE TITLE
Update awslabs/kubernetes-iteration-toolkit to use new 1.22+ versions

### ISSUE THREAD

**Issue by kschumy** [aws/eks-distro#1174]
https://github.com/awslabs/kubernetes-iteration-toolkit uses EKS-D as their version of K8s. They are using outdated versions and outdated versions of certain proejcts (e.g. etcd)

**Comment by premdass** [comment]
Hi, i would like to take a stab at this as a first issue. However i would like to have some clarifications if possible please. I can see that KIT is already using 1.23 here https://github.com/sushimaAws/kubernetes-iteration-toolkit/blob/main/operator/pkg/utils/imageprovider/imageprovider.go#L23 . So we need a way to pin etcd, coredns, AWSIamAuthenticator , AWSIamAuthenticator against certain k8s versions right ?

**Comment by kschumy** [comment]
Hi @premdass! Thank you for your interest in this. We'd need to update their versions the latest for each of the Kubernetes versions as well as the other projects.

[These lines](https://github.com/awslabs/kubernetes-iteration-toolkit/blob/main/operator/pkg/utils/imageprovider/imageprovider.go#L33-L37) need to be changed: 
``` Go
kubeVersion119Tag = "v1.19.13-eks-1-19-9"   // change to "v1.19.16-eks-1-19-22"
kubeVersion120Tag = "v1.20.7-eks-1-20-6"   // change to "v1.20.15-eks-1-20-22"
kubeVersion121Tag = "v1.21.2-eks-1-21-4"    // change to "v1.21.14-eks-1-21-20"
kubeVersion122Tag = "v1.22.6-eks-1-22-5"  // change to "v1.22.15-eks-1-22-12"
kubeVersion123Tag = "v1.23.9-eks-1-23-5"  // change to "v1.23.12-eks-1-23-7"
```

And for the second part, you're correct. We would need to allow for etcd, coredns, and iamAuth to return different versions based on the Kubernetes versions. 

As of today, these are the versions, though they may change. The easiest way to them is to look at `https://github.com/aws/eks-distro/blob/main/docs/contents/releases/1-<##>/<LATEST VERSION>/index.md`

**1.19**
etcd: v3.4.18-eks-1-19-22
coredns: v1.8.0-eks-1-19-22
iamAuth: v0.5.9-eks-1-19-22
 
**1.20**
etcd:  v3.4.21-eks-1-20-22
coredns: v1.8.3-eks-1-20-22
iamAuth: v0.5.9-eks-1-20-22

**1.21**
etcd:  v3.4.21-eks-1-21-20
coredns: v1.8.4-eks-1-21-20
iamAuth: v0.5.9-eks-1-21-20

**1.22**
etcd: v3.5.4-eks-1-22-12
coredns: v1.8.7-eks-1-22-12
iamAuth: v0.5.9-eks-1-22-12
 
 **1.23**
etcd: v3.5.4-eks-1-23-7
coredns: v1.8.7-eks-1-23-7
iamAuth: v0.5.9-eks-1-23-7

**Comment by markapruett** [comment]
Do they need 1.19 and 1.20 now that both are out of support?
