### ISSUE TITLE
Have projects' (etcd, etc) versions change depending on k8s version in awslabs/kubernetes-iteration-toolkit

### ISSUE THREAD

**Issue by kschumy** [aws/eks-distro#1175]
See https://github.com/aws/eks-distro/issues/1174 for context

They are using an old versions of EKS-Distro and mismatched project versions. They should update to the latest EKS-D and the correct project versions for each version.

**Comment by markapruett** [comment]
What is this tool and how are they using EKS-D? I would prefer if they subscribed to our SNS and triggered off those for new builds on their side.

**Comment by AashutoshPrasad77** [comment]
I want to work on this issue .
