### ISSUE TITLE
using aws sdk inside eks node corrupts files

### ISSUE THREAD

**Issue by lfvillavicencio** [aws/eks-distro#1374]
**What happened**: Several kind of microservices were deployed inside EKS Cluster as a pod to try to upload files to s3. Since eks has KMS encryption by default, when we try to upload a file using a microservice inside a pod of EKS, the file gets corrupted into S3. If we download the file from s3 it will be corrupted. tested with .docx files on java and python microservices using aws sdk for both languages

**What you expected to happen**: the files uploaded should not be corrupted.

**How to reproduce it (as minimally and precisely as possible)**: run any EKS. Run a simple python app  as a pod that reads a file from your local trough a minimal web interface, using the BOTO3 SDK for AWS use the upload object api to upload to a encrypted bucket with KMS a file. Download that file and it will be corrupted.

**Anything else we need to know?**: 

**Environment**:
- EKS Distro Release Channel:
- EKS Distro Release:

**Comment by markapruett** [comment]
Thanks for submitting this issue @lfvillavicencio. To clarify, are you using the managed EKS or have you created your own cluster using the eks-distro images and binaries?

**Comment by lfvillavicencio** [comment]
> Thanks for submitting this issue @lfvillavicencio. To clarify, are you using the managed EKS or have you created your own cluster using the eks-distro images and binaries?

Hi!. Im using the managed EKS service. Cluster has enabled KMS encryption

**Comment by markapruett** [comment]
Unfortunately,I don't think I'll be able to help you with you. This repo is just for producing the AWS Kubernetes distro, EKS-D, and not for managed EKS itself. To help you with this issue, I suggest reaching out to [AWS support](https://aws.amazon.com/premiumsupport/knowledge-center/get-aws-technical-support/). From you description it sounds like it might be more of a KMS/S3 issue than an EKS one. Closing this issue out.
