### ISSUE TITLE
failed to pull image "public.ecr.aws/eks-distro/kubernetes/pause:3.2"

### ISSUE THREAD

**Issue by LochanRn** [aws/eks-distro#140]
**What happened**:
Hi Team,
I am trying to deploy an eks-d using Kubeadm. 
Docs I referred to --> https://distro.eks.amazonaws.com/users/install/kubeadm/
I used the same kube.yaml file provided in the above documentation, edited the values containing {{ }}

Error While running command Kubeadm init --config kube.yaml

`
[preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image public.ecr.aws/eks-distro/kubernetes/pause:3.2: output: Error response from daemon: manifest for public.ecr.aws/eks-distro/kubernetes/pause:3.2 not found: manifest unknown: Requested image not found
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:147
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.18.1-beta.0.38+49aac775931dd1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
`

I checked the ecr for the image versions of pause here https://gallery.ecr.aws/?searchTerm=eks-distro&verified=verified
ECR only contains  public.ecr.aws/eks-distro/kubernetes/pause:v1.18.9-eks-1-18-1

public.ecr.aws/eks-distro/kubernetes/pause:3.2 image is not available in the ecr.

**What you expected to happen**:
Expected all the preflight requests to pass and launch the control plane node.

**How to reproduce it (as minimally and precisely as possible)**:
docker pull public.ecr.aws/eks-distro/kubernetes/pause:3.2

**Anything else we need to know?**:
I think the error is related to this issue as well https://github.com/aws/eks-distro/pull/108
Can you please add some documentation/example kube.yaml for Kubeadm join as well.

**Comment by TerryHowe** [comment]
Yes, it is related to #108 and it will be fixed for 1.19 for sure.

**Comment by bboreham** [comment]
Could you just run the tagging now please?  Pause isn't going to change before the release.

**Comment by LochanRn** [comment]
Okay, will try it. Can I know when is the release date for 1.19 ?

**Comment by abhay-krishna** [comment]
Can you retry using the pause container image with the URI `public.ecr.aws/eks-distro/kubernetes/pause:3.2`? It should work now. Please let us know if it doesn't.
```bash
$ docker pull public.ecr.aws/eks-distro/kubernetes/pause:3.2
3.2: Pulling from eks-distro/kubernetes/pause
30311302e823: Pull complete 
Digest: sha256:20ff27d990014d805c8da39a6a03f9575ac476d5c2e1b3278d70ae6c832cc34b
Status: Downloaded newer image for public.ecr.aws/eks-distro/kubernetes/pause:3.2
public.ecr.aws/eks-distro/kubernetes/pause:3.2
```

**Comment by LochanRn** [comment]
docker pull public.ecr.aws/eks-distro/kubernetes/pause:3.2 works just fine. !! I am also able to deploy eke-d using Kubeadm. Thanks for the fix.

**Comment by abhay-krishna** [comment]
> docker pull public.ecr.aws/eks-distro/kubernetes/pause:3.2 works just fine. !! I am also able to deploy eks-d using Kubeadm. Thanks for the fix.

That is awesome! Thanks for trying out EKS Distro! Do reach out if you have further issues or to make contributions.
