### ISSUE TITLE
Releases:  1.21-21, 1.22-13, 1.23-8, 1.24-3

### ISSUE THREAD

**Issue by kschumy** [aws/eks-distro#1400]
### Handle Existing PRs and Start Code Freeze for Non-Release Related Changes
- [x] For PRs created by `eks-distro-pr-bot` in the below repos, review and merge changes
  - [x] [eks-distro](https://github.com/aws/eks-distro/pulls/eks-distro-pr-bot)
  - [x] [eks-distro-build-tooling](https://github.com/aws/eks-distro-build-tooling/pulls/eks-distro-pr-bot)
  - [x] [eks-distro-prow-jobs](https://github.com/aws/eks-distro-prow-jobs/pulls/eks-distro-pr-bot)
- [x]  For non-EKS-D-bot PRs in the below repos,  review and merge all un-held/non-WIP/production-ready/non-breaking PRs intended for the release or release process; follow up with the authors of the remaining PRs about if the changes are intended for the release and, if so, what additional work needs to be done.
  - [x] [eks-distro](https://github.com/aws/eks-distro/pulls?q=is%3Apr+is%3Aopen+-author%3Aeks-distro-pr-bot)
  - [x] [eks-distro-build-tooling](https://github.com/aws/eks-distro-build-tooling/pulls?q=is%3Apr+is%3Aopen+-author%3Aeks-distro-pr-bot)
  - [x] [eks-distro-prow-jobs](https://github.com/aws/eks-distro-prow-jobs/pulls?q=is%3Apr+is%3Aopen+-author%3Aeks-distro-pr-bot)

### Check for and Make Any Additional Release-Related Changes
- [x]  Check for new project versions
  - [x] kubernetes/kubernetes
    - [x] #1407
  - [x] containernetworking/plugins
    - [x] #1408
    - [x] #1409
    - [x] #1410
  - [x] coredns/coredns
  - [x] [kubernetes-sigs/metrics-server](https://github.com/kubernetes-sigs/metrics-server/releases)
  - [x] [kubernetes-sigs/aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator/releases)
    - [x] #1403
    - [x] #1404
    - [x] #1405
    - [x] #1406
  - [x] etcd-io/etcd
  - [x] [kubernetes-csi/external-attacher](https://github.com/kubernetes-csi/external-attacher/releases)
  - [x] [kubernetes-csi/external-provisioner](https://github.com/kubernetes-csi/external-provisioner/releases)
  - [x] [kubernetes-csi/external-resizer](https://github.com/kubernetes-csi/external-resizer/releases)
  - [x] [kubernetes-csi/external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter/releases)
  - [x] [kubernetes-csi/livenessprobe](https://github.com/kubernetes-csi/livenessprobe/releases)
    - [x] #1411
    - [x] #1412
    - [x] #1413
    - [x] #1414
  - [x] #1415
    - [x] #1416
    - [x] #1417
    - [x] #1418
    - [x] #1419
- [x] Check for patch changes for ALL PROJECTS
- [x] Backport CVE changes to all supported versions
  - [x] https://github.com/aws/eks-distro/issues/1429
  - [x] https://github.com/aws/eks-distro/issues/1435

After all the release-related changes are done, recheck for new PRs created by `eks-distro-pr-bot` in the below repos; review and merge them
- [x] [eks-distro](https://github.com/aws/eks-distro/pulls/eks-distro-pr-bot)
 - [x] [eks-distro-build-tooling](https://github.com/aws/eks-distro-build-tooling/pulls/eks-distro-pr-bot)
 - [x] [eks-distro-prow-jobs](https://github.com/aws/eks-distro-prow-jobs/pulls/eks-distro-pr-bot)

---

### Cut Release
- [x] #1447
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `dev-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1454
- [x] Confirm prod release was successful
  - [x] [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `prod-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
  - [x]  Release manifest is available and looks right (`https://distro.eks.amazonaws.com/kubernetes-1-XX/kubernetes-1-XX-eks-Z.yaml`)
  - [x] Images are in [ECR](https://gallery.ecr.aws/eks-distro) 

### Announce Release
- [x] Update docs (`RELEASE_BRANCH=1-XX make docs` + additional manual changes) and get someone to actually review PR
- [x] Confirm docs changes
  - [x] Check [website](https://distro.eks.amazonaws.com/) was updated
  - [x] Check that SNS was received
- [x] Tag release (`RELEASE_GIT_TAG=v1-XX-eks-Z RELEASE_GIT_COMMIT_HASH=<docs_commit_hash> make tag)`
- [x] Generate [Release on GitHub](https://github.com/aws/eks-distro/releases) from tag  (`RELEASE_BRANCH=1-XX make github-release`)
- [x] Notify Slack channel

---

### Cut Release
- [x] #1448
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `dev-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1450
- [x] Confirm prod release was successful
  - [x] [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `prod-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
  - [x]  Release manifest is available and looks right (`https://distro.eks.amazonaws.com/kubernetes-1-XX/kubernetes-1-XX-eks-Z.yaml`)
  - [x] Images are in [ECR](https://gallery.ecr.aws/eks-distro) 

### Announce Release
- [x] Update docs (`RELEASE_BRANCH=1-XX make docs` + additional manual changes) and get someone to actually review PR
- [x] Confirm docs changes
  - [x] Check [website](https://distro.eks.amazonaws.com/) was updated
  - [x] Check that SNS was received
- [x] Tag release (`RELEASE_GIT_TAG=v1-XX-eks-Z RELEASE_GIT_COMMIT_HASH=<docs_commit_hash> make tag)`
- [x] Generate [Release on GitHub](https://github.com/aws/eks-distro/releases) from tag  (`RELEASE_BRANCH=1-XX make github-release`)

---

### Cut Release
- [x] #1449
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `dev-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1451
- [x] Confirm prod release was successful
  - [x] [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `prod-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
  - [x]  Release manifest is available and looks right (`https://distro.eks.amazonaws.com/kubernetes-1-XX/kubernetes-1-XX-eks-Z.yaml`)
  - [x] Images are in [ECR](https://gallery.ecr.aws/eks-distro) 

### Announce Release
- [x] Update docs (`RELEASE_BRANCH=1-XX make docs` + additional manual changes) and get someone to actually review PR
- [x] Confirm docs changes
  - [x] Check [website](https://distro.eks.amazonaws.com/) was updated
  - [x] Check that SNS was received
- [x] Tag release (`RELEASE_GIT_TAG=v1-XX-eks-Z RELEASE_GIT_COMMIT_HASH=<docs_commit_hash> make tag)`
- [x] Generate [Release on GitHub](https://github.com/aws/eks-distro/releases) from tag  (`RELEASE_BRANCH=1-XX make github-release`)

---

### Cut Release
- [x] #1453
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `dev-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1452
- [x] Confirm prod release was successfu
  - [x] [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `prod-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
  - [x]  Release manifest is available and looks right (`https://distro.eks.amazonaws.com/kubernetes-1-XX/kubernetes-1-XX-eks-Z.yaml`)
  - [x] Images are in [ECR](https://gallery.ecr.aws/eks-distro) 

### Announce Release
DO NOT DO ANYTHING

---

## Update Other Projects 
- [x] #1464
- [x] Update BottleRocket PRs  –– 1.22 - 1.24 only (see [example](https://github.com/bottlerocket-os/bottlerocket/pull/2230))
- [x] Update Rover
- [x] Update slack (ONLY FOR 1.21 - 1.23)

**Comment by captn3m0** [comment]
Is there a reason why 1.24-3 wasn't announced? It is listed on the [AWS Docs](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html#platform-versions-1.24) as `eks.3`, but there is no corresponding tag on this repo.

Noticed, because links at <https://endoflife.date/amazon-eks> broke for this release.

**Comment by markapruett** [comment]
Thanks @captn3m0. You should rely on the versions in [that table](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html) and not the releases in this repo for Amazon EKS's official release versions. Because it runs as a managed service in the cloud, EKS contains additional code on top of open source k8s, and that means the releases don't map 1-to-1.
