### ISSUE TITLE
Documentation regarding kubelet version.

### ISSUE THREAD

**Issue by LochanRn** [aws/eks-distro#142]
Is there any specific version of kubelet we need to use or is it compatible with the upstream Kubernetes ?

**Comment by TerryHowe** [comment]
You can get away with running a kubelet version that is compatible to whatever EKS-D you are running, but we build kubelet from upstream and potentially patch it. I don't know about 1.18 kubelet, but 1.19 we'll be patching for a CVE. 1.19 is not available yet. Check out the CRD in the docs it lists the build artifacts associated with the release:

https://distro.eks.amazonaws.com/releases/v1-18-eks-1/
