### ISSUE TITLE
Releases: 1.22-14, 1.23, and 1.24-4

### ISSUE THREAD

**Issue by kschumy** [aws/eks-distro#1475]
### Update Kubernetes Version
- [x] #1476
- [x] #1477

### Cut Release of 1.22-14
- [x] #1478
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `dev-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1479
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `prod-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1480
- [x] Confirm docs were updated
- [x] Tag release 
- [x] Generate release on GitHub

### Cut Release of 1.23-9
- [x] #1478
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `dev-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1479
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `prod-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1480
- [x] Confirm docs were updated
- [x] Tag release 
- [x] Generate release on GitHub

### Cut Release of 1.24-4
- [x] #1481
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `dev-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1482
- [x] Confirm [Prow jobs](https://prow.eks.amazonaws.com/?repo=aws%2Feks-distro&type=postsubmit&job=*1-2*) `prod-release-1-XX-postsubmit` and `build-1-XX-postsubmit` finished successfully
- [x] #1483
- [x] Confirm docs were updated
- [x] Tag release 
- [x] Generate release on GitHub

### Update Other Projects (ONLY DO ONCE BOTH RELEASES ARE OUT)
- [x] Notify Slack channel
- [x] #1484
- [x] #1486
- [x] #1485

**Comment by rcrozean** [comment]
We have finished release. I believe this is ready to close.
