### ISSUE TITLE
`GRPCContainerProbe` feature is not enabled when upgrading to version 1.24

### ISSUE THREAD

**Issue by yuvalshi0** [aws/eks-distro#1493]
Hi,
I upgraded my eks cluster from 1.23 -> 1.24 in order to add the new [gRPC liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe), yet when I try to raise my pods with the new syntax is receive the issue: `spec.containers[0].livenessProbe: Required value: must specify a handler type`, meaning the `api-server` does not takes the new `grpc` handler into consideration. 

Does the `GRPCContainerProbe` feature enabled in eks?

**Comment by TerryHowe** [comment]
How did you do the upgrade? Are you using EKS Anywhere?

**Comment by yuvalshi0** [comment]
> How did you do the upgrade? Are you using EKS Anywhere?

I'm using it in my terraform (using the [eks terraform module](https://github.com/terraform-aws-modules/terraform-aws-eks), version 18), and I upgraded by simply promoting the `cluster-version`

**Comment by markapruett** [comment]
Thanks @yuvalshi0. 

Looking at [the docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) gRPC for liveness is a beta feature and I'm not sure if EKS has enabled this yet: 
> You must enable the GRPCContainerProbe [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) in order to configure checks that rely on gRPC.

EKS Anywhere/EKS Distro is distinct from EKS and doesn't have a terraform module. I would suggest reaching out to AWS Support or other EKS support channels for assistance.
