### ISSUE TITLE
Entry point wrong for k8s container images

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-distro#1498]
**What happened**:
Entry point wrong for kube-scheduler image

**What you expected to happen**:
To run kube-scheduler

**How to reproduce it (as minimally and precisely as possible)**:
```
% docker run  public.ecr.aws/eks-distro/kubernetes/kube-scheduler:v1.22.15-eks-1-22-13  
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/local/bin/go-runner": stat /usr/local/bin/go-runner: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Anything else we need to know?**:
works
```
docker run --entrypoint kube-scheduler public.ecr.aws/eks-distro/kubernetes/kube-scheduler:v1.22.15-eks-1-22-13
```

**Environment**:
- EKS Distro Release Channel:
- EKS Distro Release: 1.22

**Comment by TerryHowe** [comment]
from https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/docker/Dockerfile#L26

**Comment by nsagark** [comment]
Can you please tell me exactly which files needs to be updated for api-server?
