### ISSUE TITLE
Open latest SDK patch upstream for supported versions

### ISSUE THREAD

**Issue by markapruett** [aws/eks-distro#1579]
Two SDK patches were upstream'd recently: https://github.com/kubernetes/kubernetes/pull/113084

Another patch was added: https://gitlab.aws.dev/eks-dataplane/eks-kubernetes-patches/-/blob/mainline/patches/1.25/0-public/0008-EKS-PATCH-Update-aws-sdk-go-from-v1.44.107-to-v1.44..patch

Open a new PR to upstream this latest patch to all supported versions.

**Comment by kschumy** [comment]
They already did this for 1.27. We can't cherry-pick to older versions because it does not seem to fit [upstream's parameters for cherry-picking](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks)
