### ISSUE TITLE
code fenced areas in docs getting clipped/truncated

### ISSUE THREAD

**Issue by aceeric** [aws/eks-distro#1717]
Please refer to: https://distro.eks.amazonaws.com/users/install/kubeadm-onsite/

In Chrome Version 109.0.5414.119 (Official Build) (64-bit) running on Amazon Linux 2, the code snippets are getting clipped. Meaning - there is no horizontal scroll bar and - in these code snippets that are clearly clipped, the _copy to clipboard_ hover icon also appears to not be available. Is this possibly doc gen issue?

Example:

![image](https://user-images.githubusercontent.com/24485843/216064843-028c7602-1ab1-4808-bbe0-c7f2664128af.png)
Without copy/paste the example can't be followed from the docs..

**Comment by markapruett** [comment]
Fixed by https://github.com/aws/eks-distro/pull/1727
