### ISSUE TITLE
Other CNI support

### ISSUE THREAD

**Issue by yiyan-wish** [aws/eks-distro#206]
Currently eks only support aws-vpc-cni, does eks-d support other cnis ?

**Comment by TerryHowe** [comment]
EKS-D has a CNI plugin and leaves it up to the user to select a CNI.  You'll need to select something other than aws-vpc-cni to run EKS-D outside of AWS.

On personal projects, I've used Flannel on some Raspberries and Calico on another project. I have not made any attempt to evaluate CNIs though

**Comment by olemarkus** [comment]
Specifically, if you use EKS-D with kOps, you will be able to use any CNI that kOps support. So you do not really have to manage CNI yourself, just specify which one you want to use.

**Comment by jaxesn** [comment]
Thanks @TerryHowe and @olemarkus!  I am going to close this one out, but if you have more questions feel free to comment more.
