### ISSUE TITLE
RUN iptables-wrapper script in EKS_DISTRO_MINIMAL_BASE_IPTABLES image

### ISSUE THREAD

**Issue by jdn5126** [aws/eks-distro#2160]
**What would you like to be added**:
I would like the EKS_DISTRO_MINIMAL_BASE_IPTABLES image to invoke the `iptables-wrapper` script that it packages rather than rely on images built on top of this base to invoke it.

**Why is this needed**:
Some images built on top of this base do not have the flexibility to modify their build recipes. Invoking this should be harmless, as it is what upstream k8s recommends anyway.

**Comment by jaxesn** [comment]
Ill take this one

**Comment by kschumy** [comment]
Fixed by above PR in build tooling
