### ISSUE TITLE
Kops is unable to read kube-apiserver.docker_tag with error 403 Forbidden

### ISSUE THREAD

**Issue by GeorgeJose7** [aws/eks-distro#2857]
I am trying to inst EKD with the kops installer provided in the eks Distro git repository.
I am receiving the following error 

```console 
Error: error building complete spec: error reading tag file "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/9/artifacts/kubernetes/v1.29.1/bin/linux/amd64/kube-apiserver.docker_tag": unexpected response code "403 Forbidden" for "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/9/artifacts/kubernetes/v1.29.1/bin/linux/amd64/kube-apiserver.docker_tag": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>T0BGSATJPBWMZMD9</RequestId><HostId>8J2lhcoPyzkdTcotGkJpkl2hlNUHhRaqyDJMm8rZ/vNix/Z6/Lfoh+WkFYgaqnMPASA7UtWSbQ0=</HostId></Error>
```

What is a possible resolution for this error?

# AWS CLI version
```console
aws-cli/2.11.13 Python/3.11.3 Darwin/23.4.0 exe/x86_64 prompt/off
```

**Comment by rcrozean** [comment]
Can you provide additional steps that you are using to reproduce this error?

**Comment by zepouet** [comment]
Hello @GeorgeJose7 @rcrozean I had the same error. This other issue helps me to understand : https://github.com/aws/eks-distro/issues/1245

Indeed we need to define a new env variable as "export RELEASE_ENVIRONMENT=production". 
You can scroll the repo there to see which version you can use https://github.com/aws/eks-distro/blob/main/release/1-29/production/RELEASE

I will try to do a PR into the doc for kops usage.
Thanks. It seems to be great now
Regards

**Comment by rcrozean** [comment]
Thank you for your help @zepouet!

**Comment by sahil-2810** [comment]
Did it resolved ?
