### ISSUE TITLE
proxy kubeconfig file missing

### ISSUE THREAD

**Issue by zencircle** [aws/eks-distro#374]
**What happened**:
```
ps aux | grep kube-proxy
root      5567  0.0  0.2 743612 43668 ?        Ssl  May05   5:24 kube-proxy --v=2 --config=/var/lib/kube-proxy-config/config

cat /var/lib/kube-proxy-config/config
cat: /var/lib/kube-proxy-config/config: No such file or directory
```
**What you expected to happen**:
Should be able to review the contents of the file `/var/lib/kube-proxy-config/config`

**How to reproduce it (as minimally and precisely as possible)**:
Deploy eks cluster
```
kubectl version
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Anything else we need to know?**:

**Environment**:
- EKS Distro Release Channel:
- EKS Distro Release:

**Comment by TerryHowe** [comment]
How did you deploy the cluster and on what operating system?

**Comment by zencircle** [comment]
EKS is deployed via AWS Console. Managed node groups;  AMI version 1.19.6-20210501. 
```
uname -a
Linux ip-10-153-130-177.cfpb.local 5.4.110-54.182.amzn2.x86_64 #1 SMP Fri Apr 9 17:56:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TerryHowe** [comment]
This repository is just for the Kubernetes distribution that is used for EKS, not about how EKS is run in AWS. Let me ask around to find out how to direct your question.

**Comment by TerryHowe** [comment]
This maybe? https://stackoverflow.com/questions/64648243/kubernetes-kube-proxy-is-running-but-the-specified-kubeconfig-file-cannot-be-fou 

Either way, you are better off going through the normal support channels for EKS.
