### ISSUE TITLE
Docs: Access Denied

### ISSUE THREAD

**Issue by jlpettersson** [aws/eks-distro#41]
**What happened**:

Getting "Access Denied" when accessing the documentation page. URL https://distro.eks.amazonaws.com/

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E88503E37DCAB5C2</RequestId>
<HostId>wAa+as8c0S44Xn+SJlhMzVf0imIz9PDl3TUGESxF3Ugo3oAfCYy5F+sE7laeI9mavQWYchjDf+g=</HostId>
</Error>
```

**What you expected to happen**:

That I can access the documentation

**How to reproduce it (as minimally and precisely as possible)**:

    curl  https://distro.eks.amazonaws.com/ -i

the output should not have status 403

**Anything else we need to know?**:

**Environment**:
- EKS Distro Release Channel:
- EKS Distro Release:

**Comment by mhausenblas** [comment]
Yup, thanks, we're aware of it and in the process of addressing this as we speak. Please stand by and in the mean time you could have a look at https://github.com/aws/eks-distro/tree/main/docs/contents which has the contents of the docs you'll find soon via https://distro.eks.amazonaws.com/

**Comment by TerryHowe** [comment]
Working now https://distro.eks.amazonaws.com/
