### ISSUE TITLE
Improved README.md

### ISSUE THREAD

**Issue by ronaldpetty** [aws/eks-distro#671]
Hello,
A link(s) on the main AWS site points here. I was hoping this would explain how to install/use EKS-DISTRO, but the README.md is about building docs. It is unclear what the 'built' docs are even for (for example, would it show you an example of installing EKS-D?).

For those who are new to EKS-D, I think the README.md should start with information about EKS-D, not how to build some documentation.

Maybe there is a page that does all the 'basics', but I have yet to find it. I know I will though as soon as I hit "Submit new issue" :)

**Comment by TerryHowe** [comment]
Accidentally deleted https://github.com/aws/eks-distro/pull/631

**Comment by TerryHowe** [comment]
Thanks for the heads up!
