### ISSUE TITLE
Failed to pull image public.ecr.aws/eks-distro/kubernetes/etcd:3.4.13-0 when installing with kubernetes-version v1.21.2-eks-1-21-3

### ISSUE THREAD

**Issue by wakinowen** [aws/eks-distro#754]
Hi Fellows,
I ran into issue that failed to pull image public.ecr.aws/eks-distro/kubernetes/etcd:3.4.13-0 when kubeadm init with kubernetes-version v1.21.5-eks-1-21-9

### Background
I'm trying to install the EKSD on bare metal based on the guide: https://distro.eks.amazonaws.com/users/install/kubeadm-onsite/
I installed with current latest version 1-21-9
https://distro.eks.amazonaws.com/releases/1-21/9/

### What has failed
The installation is successful.
But it failed when coming to execute kubeadm init command:

> kubeadm -v 7 init --image-repository public.ecr.aws/eks-distro/kubernetes  --kubernetes-version v1.21.5-eks-1-21-9

**The command output is:**
> root@control-plane-1:~# kubeadm -v 7 init --image-repository public.ecr.aws/eks-distro/kubernetes  --kubernetes-version v1.21.5-eks-1-21-9
> I0228 04:05:42.920153 1179099 initconfiguration.go:115] detected and using CRI socket: /var/run/dockershim.sock
> I0228 04:05:42.920723 1179099 interface.go:431] Looking for default routes with IPv4 addresses
> I0228 04:05:42.920747 1179099 interface.go:436] Default route transits interface "eno1np0"
> I0228 04:05:42.920983 1179099 interface.go:208] Interface eno1np0 is up
> I0228 04:05:42.921080 1179099 interface.go:256] Interface "eno1np0" has 2 addresses :[20.11.64.117/24 fe80::b226:28ff:fe4b:1880/64].
> I0228 04:05:42.921131 1179099 interface.go:223] Checking addr  20.11.64.117/24.
> I0228 04:05:42.921152 1179099 interface.go:230] IP found 20.11.64.117
> I0228 04:05:42.921174 1179099 interface.go:262] Found valid IPv4 address 20.11.64.117 for interface "eno1np0".
> I0228 04:05:42.921194 1179099 interface.go:442] Found active IP 20.11.64.117
> [init] Using Kubernetes version: v1.21.5-eks-1-21-9
> [preflight] Running pre-flight checks
> I0228 04:05:42.981821 1179099 checks.go:582] validating Kubernetes and kubeadm version
> I0228 04:05:42.981865 1179099 checks.go:167] validating if the firewall is enabled and active
> I0228 04:05:42.990740 1179099 checks.go:202] validating availability of port 6443
> I0228 04:05:42.991756 1179099 checks.go:202] validating availability of port 10259
> I0228 04:05:42.991832 1179099 checks.go:202] validating availability of port 10257
> I0228 04:05:42.991868 1179099 checks.go:287] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
> I0228 04:05:42.991889 1179099 checks.go:287] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
> I0228 04:05:42.991903 1179099 checks.go:287] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
> I0228 04:05:42.991916 1179099 checks.go:287] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
> I0228 04:05:42.991939 1179099 checks.go:437] validating if the connectivity type is via proxy or direct
> I0228 04:05:42.991982 1179099 checks.go:476] validating http connectivity to first IP address in the CIDR
> I0228 04:05:42.992010 1179099 checks.go:476] validating http connectivity to first IP address in the CIDR
> I0228 04:05:42.992022 1179099 checks.go:103] validating the container runtime
> I0228 04:05:43.036464 1179099 checks.go:129] validating if the "docker" service is enabled and active
> I0228 04:05:43.102682 1179099 checks.go:336] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
> I0228 04:05:43.102831 1179099 checks.go:336] validating the contents of file /proc/sys/net/ipv4/ip_forward
> I0228 04:05:43.102887 1179099 checks.go:654] validating whether swap is enabled or not
> I0228 04:05:43.102943 1179099 checks.go:377] validating the presence of executable conntrack
> I0228 04:05:43.103000 1179099 checks.go:377] validating the presence of executable ip
> I0228 04:05:43.103026 1179099 checks.go:377] validating the presence of executable iptables
> I0228 04:05:43.103056 1179099 checks.go:377] validating the presence of executable mount
> I0228 04:05:43.103068 1179099 checks.go:377] validating the presence of executable nsenter
> I0228 04:05:43.103081 1179099 checks.go:377] validating the presence of executable ebtables
> I0228 04:05:43.103100 1179099 checks.go:377] validating the presence of executable ethtool
> I0228 04:05:43.103112 1179099 checks.go:377] validating the presence of executable socat
> I0228 04:05:43.103124 1179099 checks.go:377] validating the presence of executable tc
> I0228 04:05:43.103152 1179099 checks.go:377] validating the presence of executable touch
> I0228 04:05:43.103167 1179099 checks.go:525] running all checks
> I0228 04:05:43.163983 1179099 checks.go:408] checking whether the given node name is valid and reachable using net.LookupHost
> I0228 04:05:43.164657 1179099 checks.go:623] validating kubelet version
> I0228 04:05:43.226445 1179099 checks.go:129] validating if the "kubelet" service is enabled and active
>         [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
> I0228 04:05:43.235205 1179099 checks.go:202] validating availability of port 10250
> I0228 04:05:43.235313 1179099 checks.go:202] validating availability of port 2379
> I0228 04:05:43.235370 1179099 checks.go:202] validating availability of port 2380
> I0228 04:05:43.235430 1179099 checks.go:250] validating the existence and emptiness of directory /var/lib/etcd
> [preflight] Pulling images required for setting up a Kubernetes cluster
> [preflight] This might take a minute or two, depending on the speed of your internet connection
> [preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
> I0228 04:05:43.282451 1179099 checks.go:850] pulling public.ecr.aws/eks-distro/kubernetes/kube-apiserver:v1.21.5-eks-1-21-9
> I0228 04:07:54.154419 1179099 checks.go:850] pulling public.ecr.aws/eks-distro/kubernetes/kube-controller-manager:v1.21.5-eks-1-21-9
> I0228 04:10:29.871136 1179099 checks.go:850] pulling public.ecr.aws/eks-distro/kubernetes/kube-scheduler:v1.21.5-eks-1-21-9
> I0228 04:11:51.677215 1179099 checks.go:844] image exists: public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.5-eks-1-21-9
> I0228 04:11:51.712994 1179099 checks.go:844] image exists: public.ecr.aws/eks-distro/kubernetes/pause:3.4.1
> I0228 04:11:51.752692 1179099 checks.go:850] pulling public.ecr.aws/eks-distro/kubernetes/etcd:3.4.13-0
> I0228 04:12:19.701682 1179099 checks.go:850] pulling public.ecr.aws/eks-distro/kubernetes/coredns:v1.8.0
> [preflight] Some fatal errors occurred:
>         [ERROR ImagePull]: failed to pull image public.ecr.aws/eks-distro/kubernetes/etcd:3.4.13-0: output: Error response from daemon: repository public.ecr.aws/eks-distro/kubernetes/etcd not found: name unknown: The repository with name 'kubernetes/etcd' does not exist in the registry with id 'eks-distro'
> , error: exit status 1
>         [ERROR ImagePull]: failed to pull image public.ecr.aws/eks-distro/kubernetes/coredns:v1.8.0: output: Error response from daemon: repository public.ecr.aws/eks-distro/kubernetes/coredns not found: name unknown: The repository with name 'kubernetes/coredns' does not exist in the registry with id 'eks-distro'
> , error: exit status 1
> [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
> error execution phase preflight
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
>         k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
>         k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
>         k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
> k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
>         k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:152
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
>         k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
>         k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
>         k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
> k8s.io/kubernetes/cmd/kubeadm/app.Run
>         k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
> main.main
>         _output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
> runtime.main
>         runtime/proc.go:225
> runtime.goexit
>         runtime/asm_amd64.s:1371

This is weird, it is attempting pulling etcd:3.4.13-0 which doesn't match what is defined in the eks-d release manifest.
In the release maniest, version of etcd says: public.ecr.aws/eks-distro/etcd-io/etcd:v3.4.16-eks-1-21-9

Can someone help on this?

### Additional info that might help
OS: ubuntu 20.04 LTS
docker version: 20.10.7 (installed by apt install docker.io)
kubeadm version is v1.21.5-eks-1-21
kubectl version is v1.21.5-eks-1-21
kubelet version is v1.21.5-eks-1-21

**Comment by jaxesn** [comment]
The kubeadm config file needs to have the etcd and coredns sections to override the tags otherwise kubeadm is going to use the default upstream tag which is why it's trying to download an image that doesn't exist in our repo.

Looking at that doc, it uses kubeadmin init with flags to override the kubernetes version and image repo. I'm not sure if there are flags for etcd and coredns. You may need to generate a kubeadm config instead and add the etcd/coredns parts then run init, passing the kubeadm config. 

The kubeadm config for etcd/coredns will look something like this

https://github.com/aws/eks-anywhere/blob/d07c35902107f4d21c785ac7ee93439cfc8177d7/pkg/executables/testdata/kind_config.yaml#L5


As a side note, if you happen to be using vsphere/vcenter as your infrastructure provider you may want to check out eks anywhere instead of self managing with kubeadm.

**Comment by wakinowen** [comment]
> The kubeadm config file needs to have the etcd and coredns sections to override the tags otherwise kubeadm is going to use the default upstream tag which is why it's trying to download an image that doesn't exist in our repo.
> 
> Looking at that doc, it uses kubeadmin init with flags to override the kubernetes version and image repo. I'm not sure if there are flags for etcd and coredns. You may need to generate a kubeadm config instead and add the etcd/coredns parts then run init, passing the kubeadm config.
> 
> The kubeadm config for etcd/coredns will look something like this
> 
> https://github.com/aws/eks-anywhere/blob/d07c35902107f4d21c785ac7ee93439cfc8177d7/pkg/executables/testdata/kind_config.yaml#L5
> 
> As a side note, if you happen to be using vsphere/vcenter as your infrastructure provider you may want to check out eks anywhere instead of self managing with kubeadm.

Thank you so much Jackson!
I will try pass a config file with coredns and etcd image repo configured then.

**Comment by wakinowen** [comment]
The issue is resolved when passing a config file to specify image tag for etcd and coredns
