### ISSUE TITLE
Migrate to CDK v2

### ISSUE THREAD

**Issue by danbudris** [aws/eks-distro#888]
EKS Distro uses CDK (cloud development kit) as an infrastructure-as-code modeling language. All of our infrastructure is defined as CDK.

We currently use CDK v1; we need to migrate to CDK v2 in order to support many new AWS features, constructors, and third party features (such as Prow features). Remaining on CDK v1 limits our ability to write modern, maintainable IaC and keep our infrastructure up-to-date.

The out come of this issue will be that all EKS Distro CDK is upgraded to CDK V2.

https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

**Comment by markapruett** [comment]
Close as duplicate
