### ISSUE TITLE
Upgrade Prow cluster k8s version to v1.22

### ISSUE THREAD

**Issue by danbudris** [aws/eks-distro#889]
Current version is 1.21. Do this for all Prow clusters. 

https://code.amazon.com/packages/AwsParisProwInfrastructureCDK/trees/mainline

**Comment by rcrozean** [comment]
CR: https://code.amazon.com/reviews/CR-83287715/revisions/1#/reviewers

**Comment by rcrozean** [comment]
Cut several updates to this. Moved to 1.22 and updated external-dns/alb as well.
