### ISSUE TITLE
ARM64 architecture support for RPi testing

### ISSUE THREAD

**Issue by paavan98pm** [aws/eks-distro#99]
**What would you like to be added**:
Add ARM64 support.

**Why is this needed**:
Since Microk8s already supports this for Raspberry Pi installs and testing, this will help a number of customers, given the EKS Anywhere announcement. https://microk8s.io/docs/install-alternatives#heading--arm

**Comment by TerryHowe** [comment]
I haven't tried arm64, but it should work https://gallery.ecr.aws/eks-distro/kubernetes/kube-apiserver for example notice it shows arm64

**Comment by jaxesn** [comment]
As @TerryHowe mentioned, arm64 builds are available for the EKS-D binaries/container images. @ktsakalozos might be able to confirm if the eks snap supports arm64 or not?

**Comment by ktsakalozos** [comment]
At this point the EKS snap is for AMD64 only, ARM support should come soon.

**Comment by TerryHowe** [comment]
The images definitely work on 64 bit Arm, Buster:
```root@rpi-159:~# uname -a
Linux rpi-159 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU/Linux
root@rpi-159:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
I have some etcd config problems, so not a running cluster at this point.

**Comment by ktsakalozos** [comment]
@paavan98pm to get the EKS snap on ARM64 currently you will to build it on an ARM^$ machine with:
```
sudo snap install snapcraft --classic
git clone https://github.com/canonical/eks-snap.git
cd eks-snap
snapcraft
```
From a quick test I did, all seemed to work apart from the storage integration with AWS.

**Comment by paavan98pm** [comment]
@ktsakalozos did you need KVM-support instance for this? It also asked for multipass. thx

**Comment by paavan98pm** [comment]
Both, R-Pi and c6g.metal returned the error below when running `snapcraft`:

```
launch failed: Internal error: qemu-system-x86_64 failed getting vmstate (Process returned exit code: 1) with output:
qemu-system-aarch64: -nographic: No machine specified, and there is no default
Use -machine help to list supported machines
```

**Comment by ktsakalozos** [comment]
@paavan98pm if qemu is not available you can build the snap in an lxd container. Instead of `snapcraft` call `snapcraft --use-lxd`.

To get lxd you can do:
```
sudo apt-get remove lxc*
sudo apt-get remove lxd*
sudo snap install lxd
lxd init --auto
```

**Comment by TerryHowe** [comment]
I think we have completed everything to support ARM for EKS-D although there may be additional work in the eks snap repository, but that can be worked on over there.
